<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Thread;
use App\User;
use App\Favorite;

class Reply extends Model
{
    use RecordsActivity, Favoritable;

    protected $guarded = [];

    protected $with = ['owner', 'favorites'];

    protected $appends = ['favoritesCount', 'isFavorited'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($reply) {
            $reply->thread->increment('replies_count');
        });

        static::deleted(function($reply) {
            $reply->thread->decrement('replies_count');
        });
    }

    public function owner()
	{
		return $this->belongsTo(User::class, 'user_id');
	}

    public function thread()
    {
    	return $this->belongsTo(Thread::class);
    }

    public function favorites()
    {
    	return $this->morphMany(Favorite::class, 'favorited');
    }

    public function path(){
	    return $this->thread->path(). "#reply-{$this->id}";
    }

}
